package com.testreports.orchestrator;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PipelineTest {
    @Test
    void runAllStages() throws Exception {
        List<String> executed = new ArrayList<>();
        List<PipelineStage> stages = List.of(
                new FakeStage("AllureGenerate", true, executed),
                new FakeStage("ManifestWrite", true, executed),
                new FakeStage("WebDeploy", false, executed),
                new FakeStage("EmailSend", false, executed)
        );

        new PipelineRunner().run(stages, context());

        assertEquals(List.of("AllureGenerate", "ManifestWrite", "WebDeploy", "EmailSend"), executed);
    }

    @Test
    void nonCriticalFailure() throws Exception {
        List<String> executed = new ArrayList<>();
        List<PipelineStage> stages = List.of(
                new FakeStage("AllureGenerate", true, executed),
                new FakeStage("WebDeploy", false, executed, new IllegalStateException("copy failed")),
                new FakeStage("EmailSend", false, executed)
        );

        new PipelineRunner().run(stages, context());

        assertEquals(List.of("AllureGenerate", "WebDeploy", "EmailSend"), executed);
    }

    @Test
    void criticalFailureStopsPipeline() {
        List<String> executed = new ArrayList<>();
        List<PipelineStage> stages = List.of(
                new FakeStage("AllureGenerate", true, executed, new IllegalStateException("allure failed")),
                new FakeStage("ManifestWrite", true, executed)
        );

        StageExecutionException thrown = assertThrows(
                StageExecutionException.class,
                () -> new PipelineRunner().run(stages, context())
        );

        assertEquals("AllureGenerate", thrown.getStageName());
        assertInstanceOf(IllegalStateException.class, thrown.getCause());
        assertEquals(List.of("AllureGenerate"), executed);
    }

    @Test
    void runIdAutoGenerated() {
        RunContext context = new RunContext("auto", null, PipelineConfig.defaults());

        assertFalse(context.getRunId().isBlank());
        assertTrue(context.getRunId().matches("\\d{8}-\\d{6}-[0-9a-f]{6}"));
    }

    private RunContext context() {
        return new RunContext("run-1", null, PipelineConfig.defaults());
    }

    private static class FakeStage implements PipelineStage {
        private final String name;
        private final boolean critical;
        private final List<String> executed;
        private final Exception failure;

        FakeStage(String name, boolean critical, List<String> executed) {
            this(name, critical, executed, null);
        }

        FakeStage(String name, boolean critical, List<String> executed, Exception failure) {
            this.name = name;
            this.critical = critical;
            this.executed = executed;
            this.failure = failure;
        }

        @Override
        public String getName() {
            return name;
        }

        @Override
        public boolean isCritical() {
            return critical;
        }

        @Override
        public void execute(RunContext ctx) throws Exception {
            executed.add(name);
            if (failure != null) {
                throw failure;
            }
        }
    }
}
